Practical 1


1 - Importing Required Python Libraries:

In [4]:
import pandas as pd
import numpy as np



2 - Locating and Describing the Dataset.
3 - Load the Dataset into pandas dataframe.

In [15]:
data = pd.read_csv('./vehicles.csv')
data.head(10)

id                                                url  \
0  7222695916  https://prescott.craigslist.org/cto/d/prescott...   
1  7218891961  https://fayar.craigslist.org/ctd/d/bentonville...   
2  7221797935  https://keys.craigslist.org/cto/d/summerland-k...   
3  7222270760  https://worcester.craigslist.org/cto/d/west-br...   
4  7210384030  https://greensboro.craigslist.org/cto/d/trinit...   
5  7222379453  https://hudsonvalley.craigslist.org/cto/d/west...   
6  7221952215  https://hudsonvalley.craigslist.org/cto/d/west...   
7  7220195662  https://hudsonvalley.craigslist.org/cto/d/poug...   
8  7209064557  https://medford.craigslist.org/cto/d/grants-pa...   
9  7219485069  https://erie.craigslist.org/cto/d/erie-2012-su...   

                   region                           region_url  price  year  \
0                prescott      https://prescott.craigslist.org   6000   NaN   
1            fayetteville         https://fayar.craigslist.org  11900   NaN   
2            florida keys          https://keys.craigslist.org  21000   NaN   
3  worcester / central MA     https://worcester.craigslist.org   1500   NaN   
4              greensboro    https://greensboro.craigslist.org   4900   NaN   
5           hudson valley  https://hudsonvalley.craigslist.org   1600   NaN   
6           hudson valley  https://hudsonvalley.craigslist.org   1000   NaN   
7           hudson valley  https://hudsonvalley.craigslist.org  15995   NaN   
8         medford-ashland       https://medford.craigslist.org   5000   NaN   
9                    erie          https://erie.craigslist.org   3000   NaN   

  manufacturer model condition cylinders  ... size  type paint_color  \
0          NaN   NaN       NaN       NaN  ...  NaN   NaN         NaN   
1          NaN   NaN       NaN       NaN  ...  NaN   NaN         NaN   
2          NaN   NaN       NaN       NaN  ...  NaN   NaN         NaN   
3          NaN   NaN       NaN       NaN  ...  NaN   NaN         NaN   
4          NaN   NaN       NaN       NaN  ...  NaN   NaN         NaN   
5          NaN   NaN       NaN       NaN  ...  NaN   NaN         NaN   
6          NaN   NaN       NaN       NaN  ...  NaN   NaN         NaN   
7          NaN   NaN       NaN       NaN  ...  NaN   NaN         NaN   
8          NaN   NaN       NaN       NaN  ...  NaN   NaN         NaN   
9          NaN   NaN       NaN       NaN  ...  NaN   NaN         NaN   

  image_url description county state lat long posting_date  
0       NaN         NaN    NaN    az NaN  NaN          NaN  
1       NaN         NaN    NaN    ar NaN  NaN          NaN  
2       NaN         NaN    NaN    fl NaN  NaN          NaN  
3       NaN         NaN    NaN    ma NaN  NaN          NaN  
4       NaN         NaN    NaN    nc NaN  NaN          NaN  
5       NaN         NaN    NaN    ny NaN  NaN          NaN  
6       NaN         NaN    NaN    ny NaN  NaN          NaN  
7       NaN         NaN    NaN    ny NaN  NaN          NaN  
8       NaN         NaN    NaN    or NaN  NaN          NaN  
9       NaN         NaN    NaN    pa NaN  NaN          NaN  

[10 rows x 26 columns]

4 - Data Preprocessing

In [6]:
# Check for missing values
missing_values = data.isnull().sum()
missing_values

id                 0
url                0
region             0
region_url         0
price              0
year              49
manufacturer     170
model             40
condition        879
cylinders        743
fuel              61
odometer          39
title_status     130
transmission      28
VIN              733
drive            638
size            1508
type             621
paint_color      467
image_url         27
description       27
county          2001
state              0
lat               39
long              39
posting_date      27
dtype: int64

In [7]:
# Get initial statistics
initial_stats = data.describe()
initial_stats


# Count: Counts the number of non-null values in each column, indicating data completeness.
# Mean: Represents the average value of each numerical column, giving a central tendency measure.
# Standard Deviation (std): Measures the dispersion of values around the mean, indicating data variability or spread.
# Minimum and Maximum: Show the lowest and highest values in each column, providing range information.
# Percentiles (25%, 50%, 75%): Indicate the values below which a given percentage of data falls, helping to understand data distribution and identify outliers.

id         price         year      odometer  county  \
count  2.001000e+03  2.001000e+03  1952.000000  1.962000e+03     0.0   
mean   7.308532e+09  5.625151e+05  2011.201332  2.038947e+05     NaN   
std    1.150144e+07  2.219042e+07     9.704075  9.915782e+05     NaN   
min    7.208550e+09  0.000000e+00  1903.000000  0.000000e+00     NaN   
25%    7.305754e+09  5.500000e+03  2008.000000  2.967350e+04     NaN   
50%    7.310397e+09  1.720000e+04  2013.000000  8.799700e+04     NaN   
75%    7.313504e+09  2.998000e+04  2017.000000  1.572288e+05     NaN   
max    7.316878e+09  9.876543e+08  2021.000000  9.999999e+06     NaN   

               lat         long  
count  1962.000000  1962.000000  
mean     33.735365   -85.549365  
std       2.167945     3.375666  
min      26.021800  -122.693000  
25%      32.922900   -86.817617  
50%      33.455361   -86.737847  
75%      33.736288   -85.480000  
max      44.120200   -73.572300

In [13]:
# Variable descriptions
# show the types of variables (character, numeric, integer, etc.).
variable_descriptions = data.dtypes
variable_descriptions

id                int64
url              object
region           object
region_url       object
price             int64
year            float64
manufacturer     object
model            object
condition        object
cylinders        object
fuel             object
odometer        float64
title_status     object
transmission     object
VIN              object
drive            object
size             object
type             object
paint_color      object
image_url        object
description      object
county          float64
state            object
lat             float64
long            float64
posting_date     object
dtype: object

5 - Data Formatting and Data Normalization

i. Data Formatting

In [22]:

# Sample data
data = {
    'ID': [1, 2, 3, 4],
    'DateOfBirth': ['1990-05-15', '1985-10-20', '1978-12-08', '1995-02-28'],
    'Salary': ['$60,000', '$45,000', '$70,000', '$55,000'],
    'IsMarried': [1, 0, 1, 0]
}
df = pd.DataFrame(data)

# Data Formatting
# Convert DateOfBirth to datetime format
print(df.dtypes)
df['DateOfBirth'] = pd.to_datetime(df['DateOfBirth'], format='%Y-%m-%d', errors='coerce')

# Convert Salary to numeric format
df['Salary'] = df['Salary'].replace('[\$,]', '', regex=True).astype(float)

# Display formatted data
print(df)
print(df.dtypes)


ID              int64
DateOfBirth    object
Salary         object
IsMarried       int64
dtype: object
   ID DateOfBirth   Salary  IsMarried
0   1  1990-05-15  60000.0          1
1   2  1985-10-20  45000.0          0
2   3  1978-12-08  70000.0          1
3   4  1995-02-28  55000.0          0
ID                      int64
DateOfBirth    datetime64[ns]
Salary                float64
IsMarried               int64
dtype: object


ii. Data Normalization

In [9]:
from sklearn.preprocessing import MinMaxScaler

# Generate sample data
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'Height': [160, 175, 180, 165],
    'Gender': ['Female', 'Male', 'Male', 'Male'],
    'IsStudent': [True, False, True, False]
}
df = pd.DataFrame(data)

# Normalization
scaler = MinMaxScaler()
numeric_cols = ['Age', 'Height']
df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

# Display normalized data
print(df)


      Name       Age  Height  Gender  IsStudent
0    Alice  0.000000    0.00  Female       True
1      Bob  0.333333    0.75    Male      False
2  Charlie  0.666667    1.00    Male       True
3    David  1.000000    0.25    Male      False


In [25]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler, Normalizer

# Generate a small dataset
np.random.seed(0)
data = np.random.randint(0, 100, size=(5, 3))
print("Original Data:")
print(data)

# 1. Min-Max Scaling
# this is Xmin and Xmax is calculated for each column
#  Xnorm = ( X - Xmin ) / ( Xmax - Xmin )

min_max_scaler = MinMaxScaler()
data_min_max = min_max_scaler.fit_transform(data)
print("\nMin-Max Scaled Data:")
print(data_min_max)

Xmin = data.min(axis=0)
Xmax = data.max(axis=0)
print(Xmin,Xmax)
data_min_max1 = (data - Xmin) / (Xmax - Xmin)

print("\nMin-Max Scaled Data1 : ")
data_min_max1 = np.reshape(data_min_max1,(5,3))
print(data_min_max1)

# 2. Z-Score Standardization
#  Xnorm = (X - mean)/std deviation
standard_scaler = StandardScaler()
data_standard = standard_scaler.fit_transform(data)
print("\nZ-Score Standardized Data:")
print(data_standard)

mean = data.mean(axis=0)
std_dev = data.std(axis=0)
data_standard_manual = (data - mean) / std_dev
print("\nManual Z-Score Standardized Data:")
print(data_standard_manual)



# 3. Robust Scaling
robust_scaler = RobustScaler()
data_robust = robust_scaler.fit_transform(data)
print("\nRobust Scaled Data:")
print(data_robust.shape)
print(data_robust)


Q1 = np.percentile(data, 25, axis=0)
Q3 = np.percentile(data, 75, axis=0)
IQR = Q3 - Q1
data_robust_manual = (data - Q1) / IQR
print("\nManual Robust Scaled Data:")
print(data_robust_manual)



# 4. Unit Vector Scaling
normalizer = Normalizer()
data_normalized = normalizer.fit_transform(data)
print("\nUnit Vector Scaled Data:")
print(data_normalized)


norms = np.linalg.norm(data, axis=1, keepdims=True)
data_normalized_manual = data / norms
print("\nManual Unit Vector Scaled Data:")
print(data_normalized_manual)

Original Data:
[[44 47 64]
 [67 67  9]
 [83 21 36]
 [87 70 88]
 [88 12 58]]

Min-Max Scaled Data:
[[0.         0.60344828 0.69620253]
 [0.52272727 0.94827586 0.        ]
 [0.88636364 0.15517241 0.34177215]
 [0.97727273 1.         1.        ]
 [1.         0.         0.62025316]]
[44 12  9] [88 70 88]

Min-Max Scaled Data1 : 
[[0.         0.60344828 0.69620253]
 [0.52272727 0.94827586 0.        ]
 [0.88636364 0.15517241 0.34177215]
 [0.97727273 1.         1.        ]
 [1.         0.         0.62025316]]

Z-Score Standardized Data:
[[-1.78420724  0.15308204  0.48610445]
 [-0.40713454  1.00353779 -1.57049131]
 [ 0.55082908 -0.95251044 -0.56088975]
 [ 0.79031998  1.13110615  1.38352806]
 [ 0.85019271 -1.33521553  0.26174855]]

Manual Z-Score Standardized Data:
[[-1.78420724  0.15308204  0.48610445]
 [-0.40713454  1.00353779 -1.57049131]
 [ 0.55082908 -0.95251044 -0.56088975]
 [ 0.79031998  1.13110615  1.38352806]
 [ 0.85019271 -1.33521553  0.26174855]]

Robust Scaled Data:
(5, 3)
[[-1.95   

6 - Turn categorical variables into quantitative variables

In [11]:
from sklearn.preprocessing import LabelEncoder

In [19]:
encoder = LabelEncoder()
df = pd.read_csv('./vehicles.csv')

df['condition_category'] = encoder.fit_transform(df['condition'])


In [20]:
df['condition_category']

0       5
1       5
2       5
3       5
4       5
       ..
1996    5
1997    5
1998    2
1999    5
2000    5
Name: condition_category, Length: 2001, dtype: int32